# Generated by Django 4.2.30 on 2026-07-14 09:35

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='Author')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Featured image')),
                ('category', models.CharField(choices=[('ACTUS', 'ACTUS'), ('MOOD', 'MOOD'), ('AGENDA', 'AGENDA'), ('BUSINESS', 'BUSINESS'), ('INVITÉ', 'INVITÉ'), ('FOCUS', 'FOCUS'), ('COVER', 'COVER'), ('BIEN-ÊTRE', 'BIEN-ÊTRE'), ('ET SI ON EN PARLAIT ?', 'ET SI ON EN PARLAIT ?'), ('LIFESTYLE', 'LIFESTYLE'), ('IMPACTFUL', 'THE MOST IMPACTFUL PERSONALITIES')], default='ACTUS', max_length=50)),
                ('chapo', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Introduction')),
                ('texte', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Article')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
