# Generated by Django 4.2.30 on 2026-07-02 10:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('chapo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('texte', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('category', models.CharField(choices=[('ACTUS', 'ACTUS'), ('MOOD', 'MOOD'), ('AGENDA', 'AGENDA'), ('BUSINESS', 'BUSINESS'), ('INVITÉ', 'INVITÉ'), ('FOCUS', 'FOCUS'), ('COVER', 'COVER'), ('BIEN-ÊTRE', 'BIEN-ÊTRE'), ('ET SI ON EN PARLAIT ?', 'ET SI ON EN PARLAIT ?'), ('LIFESTYLE', 'LIFESTYLE'), ('IMPACTFUL', 'THE MOST IMPACTFUL PERSONALITIES')], default='ACTUS', max_length=50)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
