# Generated by Django 4.2.30 on 2026-06-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_magazine', '0002_alter_article_options_remove_article_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
