# Generated by Django 4.2.30 on 2026-07-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_magazine', '0002_alter_article_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
