# Generated by Django 4.2.30 on 2026-06-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_magazine', '0003_alter_article_author_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('mood', 'Mood'), ('agenda', 'Agenda Business'), ('guest', 'Guest Focus'), ('cover', 'Cover'), ('well_being', 'Well-being'), ('what_if', 'What if we talked about it ?'), ('lifestyle', 'Lifestyle'), ('impactful', 'The Most Impactful Personalities')], default='news', max_length=50),
        ),
    ]
