# Generated by Django 4.2.30 on 2026-06-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_magazine', '0004_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='chapo',
            field=models.TextField(blank=True, help_text='Ici vous pouvez mettre le chapô', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('ACTUS', 'ACTUS'), ('MOOD', 'MOOD'), ('AGENDA', 'AGENDA'), ('BUSINESS', 'BUSINESS'), ('INVITÉ', 'INVITÉ'), ('FOCUS', 'FOCUS'), ('COVER', 'COVER'), ('BIEN-ÊTRE', 'BIEN-ÊTRE'), ('ET SI ON EN PARLAIT ?', 'ET SI ON EN PARLAIT ?'), ('LIFESTYLE', 'LIFESTYLE'), ('IMPACTFUL', 'THE MOST IMPACTFUL PERSONALITIES')], default='news', max_length=50),
        ),
    ]
