# Generated by Django 4.2.30 on 2026-06-30 09:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_magazine', '0005_article_chapo_alter_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='texte',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('ACTUS', 'ACTUS'), ('MOOD', 'MOOD'), ('AGENDA', 'AGENDA'), ('BUSINESS', 'BUSINESS'), ('INVITÉ', 'INVITÉ'), ('FOCUS', 'FOCUS'), ('COVER', 'COVER'), ('BIEN-ÊTRE', 'BIEN-ÊTRE'), ('ET SI ON EN PARLAIT ?', 'ET SI ON EN PARLAIT ?'), ('LIFESTYLE', 'LIFESTYLE'), ('IMPACTFUL', 'THE MOST IMPACTFUL PERSONALITIES')], default='ACTUS', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='chapo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
